prog:main.o menu.o animation.o jouer.o background.o personnage.o scrolling.o  scorevie.o enemy.o code.o collision.o
	gcc main.o menu.o animation.o jouer.o background.o personnage.o  scrolling.o  scorevie.o  enemy.o code.o collision.o -o prog -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -g
menu.o:menu.c
	gcc -c menu.c -g
jeu.o:jouer.c
	gcc -c jeu.c -g
animation.o:animation.c
	gcc -c animation.c -g
personnage.o:personnage.c
	gcc -c personnage.c -g
background.o:background.c
	gcc -c background.c -g
scrolling.o:scrolling.c
	gcc -c scrolling.c -g

scorevie.o:scorevie.c
	gcc -c scorevie.c -g

enemy.o:enemy.c
	gcc -c enemy.c -g
code.o:code.c
	gcc -c code.c -g
collision.o:collision.c
	gcc -c collision.c -g




